// GENERATED dari m_options (tidore_lama) — jangan edit manual.
// Peta kode → nama untuk field berkode pada payload permohonan.
export const CODE_VALUES_MASTER: Record<string, Record<string, string>> = {
  "agama": {
    "1": "Islam",
    "2": "Kristen",
    "3": "Katholik",
    "4": "Hindu",
    "5": "Budha",
    "6": "Konghuchu",
    "7": "Kepercayaan"
  },
  "golongandarah": {
    "1": "A",
    "2": "Ab",
    "3": "Ab Min",
    "4": "Ab Plus",
    "5": "A Min",
    "6": "A Plus",
    "7": "B",
    "8": "B Min",
    "9": "B Plus",
    "10": "O",
    "11": "O Min",
    "12": "O Plus",
    "13": "Tdk Th"
  },
  "pekerjaan": {
    "1": "Belum/Tidak Bekerja",
    "2": "Mengurus Rumah Tangga",
    "3": "Pelajar/Mahasiswa",
    "4": "Pensiunan",
    "5": "Pegawai Negeri Sipil",
    "6": "Tentara Nasional Indonesia",
    "7": "Kepolisian Ri",
    "8": "Perdagangan",
    "9": "Petani/Pekebun",
    "10": "Peternak",
    "11": "Nelayan/Perikanan",
    "12": "Industri",
    "13": "Konstruksi",
    "14": "Transportasi",
    "15": "Karyawan Swasta",
    "16": "Karyawan Bumn",
    "17": "Karyawan Bumd",
    "18": "Karyawan Honorer",
    "19": "Buruh Harian Lepas",
    "20": "Buruh Tani/Perkebunan",
    "21": "Buruh Nelayan/Perikanan",
    "22": "Buruh Peternakan",
    "23": "Pembantu Rumah Tangga",
    "24": "Tukang Cukur",
    "25": "Tukang Listrik",
    "26": "Tukang Batu",
    "27": "Tukang Kayu",
    "28": "Tukang Sol Sepatu",
    "29": "Tukang Las/Pandai Besi",
    "30": "Tukang Jahit",
    "31": "Tukang Gigi",
    "32": "Penata Rias",
    "33": "Penata Busana",
    "34": "Penata Rambut",
    "35": "Mekanik",
    "36": "Seniman",
    "37": "Tabib",
    "38": "Paraji",
    "39": "Perancang Busana",
    "40": "Penterjemah",
    "41": "Imam Mesjid",
    "42": "Pendeta",
    "43": "Pastor",
    "44": "Wartawan",
    "45": "Ustadz/Mubaligh",
    "46": "Juru Masak",
    "47": "Promotor Acara",
    "48": "Anggota Dpr-ri",
    "49": "Anggota Dpd",
    "50": "Anggota Bpk",
    "51": "Presiden",
    "52": "Wakil Presiden",
    "53": "Anggota Mahkamah Konstitusi",
    "54": "Anggota Kabinet/Kementerian",
    "55": "Duta Besar",
    "56": "Gubernur",
    "57": "Wakil Gubernur",
    "58": "Bupati",
    "59": "Wakil Bupati",
    "60": "Walikota",
    "61": "Wakil Walikota",
    "62": "Anggota Dprd Provinsi",
    "63": "Anggota Dprd Kabupaten/Kota",
    "64": "Dosen",
    "65": "Guru",
    "66": "Pilot",
    "67": "Pengacara",
    "68": "Notaris",
    "69": "Arsitek",
    "70": "Akuntan",
    "71": "Konsultan",
    "72": "Dokter",
    "73": "Bidan",
    "74": "Perawat",
    "75": "Apoteker",
    "76": "Psikiater/Psikolog",
    "77": "Penyiar Televisi",
    "78": "Penyiar Radio",
    "79": "Pelaut",
    "80": "Peneliti",
    "81": "Sopir",
    "82": "Pialang",
    "83": "Paranormal",
    "84": "Pedagang",
    "85": "Perangkat Desa",
    "86": "Kepala Desa",
    "87": "Biarawati",
    "88": "Wiraswasta",
    "89": "Lainnya"
  },
  "pendidikan": {
    "1": "Tidak/Belum Sekolah",
    "2": "Belum Tamat SD/Sederajat",
    "3": "Tamat SD/Sederajat",
    "4": "SLTP/Sederajat",
    "5": "SLTA/Sederajat",
    "6": "Diploma I/II",
    "7": "Akademi/Diploma III",
    "8": "Diploma IV/Strata I",
    "9": "Strata II",
    "10": "Strata III"
  },
  "statusperkawinan": {
    "1": "Belum Kawin",
    "2": "Kawin",
    "3": "Cerai Hidup",
    "4": "Cerai Mati"
  }
};
